baseURL = 'https://thankful-plant-0dfb5520f.1.azurestaticapps.net'
languageCode = 'en-us'
title = 'Stef & Laz - BodaPest 2027'

[params]
    weddingDate = "2027-06-25T18:00:00"
    venueName = "Európa Hajó, Budapest"
    contactEmail = "stef.laz.wedding@gmail.com"
